name: Deploy to github pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # uses GitHub's checkout action to checkout code form the master branch
      - uses: actions/checkout@v4
      # sets up .NET Core SDK 
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 7.0
      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish site/site.csproj -c Release -o release --nologo
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
